"""Phone-number → ProspectRecord lookup for the transcript pipeline.

Fully local — scans the daily call-list CSVs on disk. No network calls,
no DynamoDB, works offline. Covers all prospects dialed by hand or via
Vapi as long as their CSV was generated by the prospecting workcell.

Lookup order:
  1. Scan call_list_YYYY-MM-DD.csv files (most-recent first, up to 60 days)
  2. Return the first ProspectRecord whose normalized phone matches

Phone normalisation: strip all non-digits, then compare the last 10 digits
(US numbers). This handles E.164, local 10-digit, 11-digit with leading 1,
and common formatted variants like (555) 123-4567.
"""
from __future__ import annotations

import csv
import logging
import re
from datetime import date, timedelta
from pathlib import Path

from backend.common import storage
from backend.prospecting.csv_export import CSV_COLUMNS
from backend.prospecting.models import ProspectRecord

_LOG = logging.getLogger("samus.voice.prospect_lookup")

_DAILY_CALLS_SUBDIR = "daily_calls"
_LOOKBACK_DAYS = 60

# Fallback artifact roots searched when SAMUS_ARTIFACT_ROOT doesn't have the CSVs.
# Covers both host-mode (D:\...\.data\host_artifacts) and container-mode
# (E:\...\artifacts) layouts so the lookup works regardless of which env the
# agent is running under.
_FALLBACK_ROOTS = (
    Path(r"D:\Hustleforge\Samus\.data\host_artifacts"),
    Path(r"E:\Hustleforge\Samus\data\artifacts"),
)


def _candidate_daily_dirs() -> list[Path]:
    """Return all existing daily_calls directories worth scanning."""
    seen: list[Path] = []
    primary = storage.root() / _DAILY_CALLS_SUBDIR
    if primary.exists():
        seen.append(primary)
    for root in _FALLBACK_ROOTS:
        d = root / _DAILY_CALLS_SUBDIR
        if d.exists() and not any(d.samefile(s) for s in seen):
            seen.append(d)
    return seen


def _digits(phone: str) -> str:
    """Return only the digit characters from a phone string."""
    return re.sub(r"\D", "", phone or "")


def _norm10(phone: str) -> str:
    """Normalize to last 10 digits for US number comparison."""
    d = _digits(phone)
    return d[-10:] if len(d) >= 10 else d


def lookup_by_phone(phone: str) -> ProspectRecord | None:
    """Return the most-recently-contacted ProspectRecord matching ``phone``.

    Scans CSVs newest-first so a prospect who appeared on a recent callsheet
    takes precedence over an older entry with the same number.
    """
    if not phone:
        return None

    target = _norm10(phone)
    if len(target) < 7:
        return None

    daily_dirs = _candidate_daily_dirs()
    if not daily_dirs:
        return None

    today = date.today()
    for days_back in range(_LOOKBACK_DAYS + 1):
        d = today - timedelta(days=days_back)
        for daily_dir in daily_dirs:
            csv_path = daily_dir / f"call_list_{d.isoformat()}.csv"
            if not csv_path.exists():
                continue
            match = _scan_csv(csv_path, target)
            if match:
                return match

    return None


def _scan_csv(path: Path, target_10: str) -> ProspectRecord | None:
    """Return the first row in ``path`` whose phone tail matches ``target_10``."""
    try:
        with path.open("r", encoding="utf-8", newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                raw_phone = row.get("phone") or ""
                if _norm10(raw_phone) == target_10:
                    payload = {
                        col: row[col]
                        for col in CSV_COLUMNS
                        if (row.get(col) or "") != ""
                    }
                    try:
                        return ProspectRecord.model_validate(payload)
                    except Exception as exc:  # noqa: BLE001
                        _LOG.debug("prospect_lookup: row parse failed in %s: %s", path.name, exc)
    except OSError as exc:
        _LOG.debug("prospect_lookup: cannot read %s: %s", path, exc)
    return None


def build_phone_index(lookback_days: int = _LOOKBACK_DAYS) -> dict[str, ProspectRecord]:
    """Build a full phone→ProspectRecord index from all recent CSVs.

    Newer CSVs win (most-recent entry per phone number is kept).
    Useful for batch pipeline runs so we only scan files once.
    """
    index: dict[str, ProspectRecord] = {}
    daily_dirs = _candidate_daily_dirs()
    if not daily_dirs:
        return index

    today = date.today()
    # Process oldest-first so newer CSVs overwrite older entries.
    # When the same date exists in multiple roots, the later root wins
    # (typically the host's host_artifacts since it's the operator path).
    paths = []
    for days_back in range(lookback_days, -1, -1):
        d = today - timedelta(days=days_back)
        for daily_dir in daily_dirs:
            p = daily_dir / f"call_list_{d.isoformat()}.csv"
            if p.exists():
                paths.append(p)

    for path in paths:
        try:
            with path.open("r", encoding="utf-8", newline="") as fh:
                reader = csv.DictReader(fh)
                for row in reader:
                    raw_phone = row.get("phone") or ""
                    key = _norm10(raw_phone)
                    if len(key) < 7:
                        continue
                    payload = {
                        col: row[col]
                        for col in CSV_COLUMNS
                        if (row.get(col) or "") != ""
                    }
                    try:
                        index[key] = ProspectRecord.model_validate(payload)
                    except Exception:  # noqa: BLE001
                        pass
        except OSError:
            pass

    _LOG.info("prospect_lookup: built index with %d entries from %d CSV(s)", len(index), len(paths))
    return index
