"""AI media generation for the website deliverable — Gemini image + Veo video.

Headless, taste-governed visual generation: hero/section imagery and full-motion
hero video for a client site. Pairs with the taste subsystem (which *requires*
real generated visuals over div-placeholders) and content_gen/seo_enrich to make
"frontier" sites.

Cost posture (non-negotiable): Gemini image + Veo video are Google-billed,
SEPARATE from the Anthropic $1/day cap. Every paid call is metered by
``backend.common.media_budget.MediaBudgetStore`` and is **dormant + keyless-safe**:
with ``website_media_gen_enabled`` off or no ``gemini_api_key`` the orchestrator
returns nothing and spends nothing. Veo video is gated again behind its own flag
+ per-video operator approval (it is the expensive part).

API (verified shapes for image; Veo marked EXPERIMENTAL — verify live with a real
key before enabling): ``POST {base}/models/{model}:generateContent`` with header
``x-goog-api-key``; response carries base64 PNG in ``inline_data``. Veo uses the
long-running ``:predictLongRunning`` + operation polling.

Delivery to Wix (uploading the generated bytes to the site's Media Manager +
binding) is the next live-verified phase — this module produces the assets; it
does not push them to Wix yet.
"""

from __future__ import annotations

import base64
import logging
import time
from dataclasses import dataclass, field
from typing import Any

import httpx

from .models import WebsiteBrief

_LOG = logging.getLogger("samus.website.media_gen")

GEMINI_BASE = "https://generativelanguage.googleapis.com/v1beta"
_IMAGE_TIMEOUT_S = 90.0
_VIDEO_START_TIMEOUT_S = 60.0
_VIDEO_POLL_TIMEOUT_S = 300.0
_VIDEO_POLL_INTERVAL_S = 10.0


class MediaGenError(Exception):
    """A media generation call failed (transport / non-200 / unparseable)."""


@dataclass
class MediaRequest:
    kind: str  # hero_image | section_image | og_image | texture | hero_video
    prompt: str
    aspect_ratio: str = "16:9"
    image_size: str = "2K"
    is_video: bool = False
    est_cost_usd: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "prompt": self.prompt,
            "aspect_ratio": self.aspect_ratio,
            "image_size": self.image_size,
            "is_video": self.is_video,
            "est_cost_usd": round(self.est_cost_usd, 4),
        }


@dataclass
class MediaAsset:
    kind: str
    prompt: str
    is_video: bool
    ok: bool
    model: str = ""
    mime_type: str = ""
    aspect_ratio: str = ""
    cost_usd: float = 0.0
    bytes_len: int = 0
    operation: str = ""  # Veo long-running operation name (video)
    video_uri: str = ""  # Veo result URI (video), when available
    error: str = ""
    data_b64: str = field(default="", repr=False)  # in-memory payload (not serialized)

    def to_dict(self) -> dict[str, Any]:
        # Raw bytes/b64 intentionally omitted — the caller persists/uploads them.
        return {
            "kind": self.kind,
            "prompt": self.prompt,
            "is_video": self.is_video,
            "ok": self.ok,
            "model": self.model,
            "mime_type": self.mime_type,
            "aspect_ratio": self.aspect_ratio,
            "cost_usd": round(self.cost_usd, 4),
            "bytes_len": self.bytes_len,
            "operation": self.operation,
            "video_uri": self.video_uri,
            "error": self.error,
        }


# --- thin HTTP wrappers (monkeypatch points in tests) ----------------------


def _http_post(
    url: str, *, json: dict[str, Any], headers: dict[str, str], timeout: float
) -> httpx.Response:
    with httpx.Client(timeout=timeout) as client:
        return client.post(url, json=json, headers=headers)


def _http_get(url: str, *, headers: dict[str, str], timeout: float) -> httpx.Response:
    with httpx.Client(timeout=timeout, follow_redirects=True) as client:
        return client.get(url, headers=headers)


# --- image -----------------------------------------------------------------


def generate_image(
    prompt: str,
    *,
    api_key: str,
    model: str = "gemini-2.5-flash-image",
    aspect_ratio: str = "16:9",
    image_size: str = "2K",
    input_image_b64: str | None = None,
    timeout: float = _IMAGE_TIMEOUT_S,
) -> bytes:
    """Generate (or edit) one image. Returns PNG bytes. Raises MediaGenError."""
    if not api_key:
        raise MediaGenError("gemini_api_key unset")
    parts: list[dict[str, Any]] = [{"text": prompt}]
    if input_image_b64:
        parts.append({"inline_data": {"mime_type": "image/png", "data": input_image_b64}})
    # gemini-2.5-flash-image: generationConfig.responseModalities + imageConfig.
    # imageSize (1K/2K/4K) is only honored by the *pro* image models, so it is
    # sent only for those to avoid a 400 on flash.
    image_config: dict[str, Any] = {"aspectRatio": aspect_ratio}
    if "pro" in model:
        image_config["imageSize"] = image_size
    body = {
        "contents": [{"parts": parts}],
        "generationConfig": {"responseModalities": ["IMAGE"], "imageConfig": image_config},
    }
    url = f"{GEMINI_BASE}/models/{model}:generateContent"
    try:
        resp = _http_post(
            url,
            json=body,
            headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
            timeout=timeout,
        )
    except httpx.HTTPError as exc:
        raise MediaGenError(f"transport: {exc}") from exc
    if resp.status_code != 200:
        raise MediaGenError(f"gemini {resp.status_code}: {resp.text[:200]}")
    b64 = _extract_image_b64(resp.json())
    if not b64:
        raise MediaGenError("no image in response")
    try:
        return base64.b64decode(b64)
    except (ValueError, TypeError) as exc:
        raise MediaGenError(f"bad base64: {exc}") from exc


def _extract_image_b64(payload: dict[str, Any]) -> str:
    """Pull the first inline image payload from a generateContent response."""
    for cand in payload.get("candidates", []) or []:
        for part in (cand.get("content", {}) or {}).get("parts", []) or []:
            inline = part.get("inlineData") or part.get("inline_data")
            if isinstance(inline, dict) and inline.get("data"):
                return str(inline["data"])
    return ""


# --- video (Veo) — EXPERIMENTAL --------------------------------------------


def start_video(
    prompt: str,
    *,
    api_key: str,
    model: str = "veo-3.1-fast-generate-preview",
    aspect_ratio: str = "16:9",
    resolution: str = "720p",
    seconds: str = "8",
    timeout: float = _VIDEO_START_TIMEOUT_S,
) -> str:
    """Kick off a Veo long-running generation (Gemini API). Returns the operation name.

    Verified shape: POST models/{model}:predictLongRunning with instances[].prompt
    + parameters{aspectRatio,resolution,durationSeconds}. Raises MediaGenError on failure.
    """
    if not api_key:
        raise MediaGenError("gemini_api_key unset")
    body = {
        "instances": [{"prompt": prompt}],
        "parameters": {
            "aspectRatio": aspect_ratio,
            "resolution": resolution,
            "durationSeconds": int(seconds),
        },
    }
    url = f"{GEMINI_BASE}/models/{model}:predictLongRunning"
    try:
        resp = _http_post(
            url,
            json=body,
            headers={"x-goog-api-key": api_key, "Content-Type": "application/json"},
            timeout=timeout,
        )
    except httpx.HTTPError as exc:
        raise MediaGenError(f"transport: {exc}") from exc
    if resp.status_code != 200:
        raise MediaGenError(f"veo start {resp.status_code}: {resp.text[:200]}")
    name = resp.json().get("name", "")
    if not name:
        raise MediaGenError("veo: no operation name returned")
    return str(name)


def poll_video(
    operation: str,
    *,
    api_key: str,
    timeout: float = _VIDEO_POLL_TIMEOUT_S,
    interval: float = _VIDEO_POLL_INTERVAL_S,
) -> dict[str, Any]:
    """Poll a Veo operation until done or ``timeout``. Returns the operation dict."""
    url = f"{GEMINI_BASE}/{operation}"
    waited = 0.0
    while waited <= timeout:
        try:
            resp = _http_get(url, headers={"x-goog-api-key": api_key}, timeout=30.0)
        except httpx.HTTPError as exc:
            raise MediaGenError(f"transport: {exc}") from exc
        if resp.status_code != 200:
            raise MediaGenError(f"veo poll {resp.status_code}: {resp.text[:200]}")
        data = resp.json()
        if data.get("done"):
            return data
        time.sleep(interval)
        waited += interval
    raise MediaGenError(f"veo operation timed out after {timeout}s")


def _extract_video_uri(operation_result: dict[str, Any]) -> str:
    """Pull the video URI from a done Veo operation.

    Verified shape: response.generateVideoResponse.generatedSamples[0].video.uri.
    Falls back across known variants so a minor API rename degrades gracefully.
    """
    resp = operation_result.get("response", {}) or {}
    gvr = resp.get("generateVideoResponse") or {}
    for listkey in ("generatedSamples", "generatedVideos", "videos", "samples"):
        node = (gvr.get(listkey) if isinstance(gvr, dict) else None) or resp.get(listkey)
        if isinstance(node, list) and node:
            v = node[0] or {}
            uri = (v.get("video", {}) or {}).get("uri") or v.get("uri") or v.get("url")
            if uri:
                return str(uri)
    return ""


def download_video(uri: str, *, api_key: str, timeout: float = 120.0) -> bytes:
    """Download a Veo result file. The generativelanguage file URI needs the API key."""
    try:
        r = _http_get(uri, headers={"x-goog-api-key": api_key}, timeout=timeout)
    except httpx.HTTPError as exc:
        raise MediaGenError(f"video download transport: {exc}") from exc
    if r.status_code != 200 or not r.content:
        raise MediaGenError(f"video download {r.status_code}")
    return r.content


# --- taste-governed plan ---------------------------------------------------


def build_media_plan(
    brief: WebsiteBrief,
    *,
    settings: Any,
    taste_profile: Any = None,
) -> list[MediaRequest]:
    """Derive the visual asset plan (prompts) from the brief + taste read."""
    name = brief.business_name
    industry = (brief.industry or "").split(",")[0].strip() or "local business"
    desc = " ".join((brief.business_description or "").split())[:200]
    colors = ", ".join(brief.brand_colors) if brief.brand_colors else "a clean, modern palette"
    img_size = str(getattr(settings, "website_media_image_size", "2K"))
    img_cost = float(getattr(settings, "media_image_cost_usd", 0.04))
    vid_cost = float(getattr(settings, "media_video_cost_usd", 0.75))

    style = (
        f"Photorealistic, high-end, modern. Brand palette: {colors}. "
        "Natural light, professional composition. No text, no words, no logos, no watermarks."
    )
    # Representation directive for any shot depicting people (diversity by default).
    people = (getattr(settings, "website_media_people_directive", "") or "").strip()
    people_suffix = f" {people}" if people else ""

    plan = [
        MediaRequest(
            "hero_image",
            f"Hero photograph for {name}, a {industry} business. {desc}. {style}{people_suffix}",
            aspect_ratio="16:9",
            image_size=img_size,
            est_cost_usd=img_cost,
        ),
        MediaRequest(
            "section_image",
            f"Authentic candid photo representing {industry} work for {name}. {style}{people_suffix}",
            aspect_ratio="4:3",
            image_size=img_size,
            est_cost_usd=img_cost,
        ),
        MediaRequest(
            "og_image",
            f"Social-share image for {name}, {industry}. {style}{people_suffix}",
            aspect_ratio="16:9",
            image_size="1K",
            est_cost_usd=img_cost,
        ),
    ]
    if getattr(settings, "website_media_video_enabled", False):
        plan.append(
            MediaRequest(
                "hero_video",
                f"Cinematic 8 second hero background video for {name}, a {industry} business. "
                f"Slow, smooth camera motion, shallow depth of field. {style}{people_suffix}",
                aspect_ratio="16:9",
                is_video=True,
                est_cost_usd=vid_cost,
            )
        )
    return plan


# --- orchestrator ----------------------------------------------------------


def generate_media(
    brief: WebsiteBrief,
    *,
    settings: Any,
    video_approved: bool = False,
) -> tuple[list[MediaAsset], dict[str, Any]]:
    """Generate the planned media under the paid-media budget. Dormant + fail-closed.

    Returns ``(assets, report)``. Returns no assets (and spends nothing) when the
    capability is off, no key is set, or the budget denies. Video is skipped
    unless ``website_media_video_enabled`` AND (approval not required OR
    ``video_approved``).
    """
    if not getattr(settings, "website_media_gen_enabled", False):
        return [], {"status": "disabled"}
    api_key = (getattr(settings, "gemini_api_key", "") or "").strip()
    if not api_key:
        return [], {"status": "no_api_key"}

    from backend.common.media_budget import MediaBudgetStore

    budget = MediaBudgetStore(float(getattr(settings, "media_daily_dollar_cap", 0.0)))
    image_model = str(getattr(settings, "website_media_image_model", "gemini-2.5-flash-image"))
    video_model = str(getattr(settings, "website_media_video_model", "veo-3.0-generate-001"))
    requires_approval = bool(getattr(settings, "media_video_requires_approval", True))

    plan = build_media_plan(brief, settings=settings)
    assets: list[MediaAsset] = []
    spent = 0.0
    skipped: list[str] = []

    for req in plan:
        if req.is_video and requires_approval and not video_approved:
            skipped.append(f"{req.kind}:video_requires_approval")
            continue
        decision = budget.can_spend(req.est_cost_usd)
        if not decision.allowed:
            skipped.append(f"{req.kind}:{decision.reason}")
            continue
        if req.is_video:
            assets.append(
                _run_video(
                    req,
                    api_key=api_key,
                    model=video_model,
                    budget=budget,
                    resolution=str(getattr(settings, "website_media_video_resolution", "720p")),
                    seconds=str(getattr(settings, "website_media_video_seconds", "8")),
                )
            )
        else:
            assets.append(_run_image(req, api_key=api_key, model=image_model, budget=budget))
        if assets[-1].ok:
            spent += assets[-1].cost_usd

    report = {
        "status": "ok",
        "planned": [r.to_dict() for r in plan],
        "generated": [a.to_dict() for a in assets],
        "skipped": skipped,
        "spent_usd": round(spent, 4),
    }
    return assets, report


def _run_image(req: MediaRequest, *, api_key: str, model: str, budget: Any) -> MediaAsset:
    try:
        data = generate_image(
            req.prompt,
            api_key=api_key,
            model=model,
            aspect_ratio=req.aspect_ratio,
            image_size=req.image_size,
        )
    except MediaGenError as exc:
        return MediaAsset(
            req.kind,
            req.prompt,
            False,
            ok=False,
            model=model,
            aspect_ratio=req.aspect_ratio,
            error=str(exc),
        )
    budget.record(req.est_cost_usd)
    return MediaAsset(
        req.kind,
        req.prompt,
        False,
        ok=True,
        model=model,
        mime_type="image/png",
        aspect_ratio=req.aspect_ratio,
        cost_usd=req.est_cost_usd,
        bytes_len=len(data),
        data_b64=base64.b64encode(data).decode("ascii"),
    )


def _run_video(
    req: MediaRequest,
    *,
    api_key: str,
    model: str,
    budget: Any,
    resolution: str = "720p",
    seconds: str = "8",
) -> MediaAsset:
    try:
        op = start_video(
            req.prompt,
            api_key=api_key,
            model=model,
            aspect_ratio=req.aspect_ratio,
            resolution=resolution,
            seconds=seconds,
        )
        result = poll_video(op, api_key=api_key)
        uri = _extract_video_uri(result)
        if not uri:
            return MediaAsset(
                req.kind,
                req.prompt,
                True,
                ok=False,
                model=model,
                aspect_ratio=req.aspect_ratio,
                operation=op,
                error="no_video_uri_in_result",
            )
        data = download_video(uri, api_key=api_key)  # Veo file needs the API key
    except MediaGenError as exc:
        return MediaAsset(
            req.kind,
            req.prompt,
            True,
            ok=False,
            model=model,
            aspect_ratio=req.aspect_ratio,
            error=str(exc),
        )
    budget.record(req.est_cost_usd)
    return MediaAsset(
        req.kind,
        req.prompt,
        True,
        ok=True,
        model=model,
        mime_type="video/mp4",
        aspect_ratio=req.aspect_ratio,
        cost_usd=req.est_cost_usd,
        operation=op,
        video_uri=uri,
        bytes_len=len(data),
        data_b64=base64.b64encode(data).decode("ascii"),
    )


__all__ = [
    "MediaGenError",
    "MediaRequest",
    "MediaAsset",
    "generate_image",
    "start_video",
    "poll_video",
    "build_media_plan",
    "generate_media",
]
