"""Auto-draft ADR stubs for blocked actions.

The Codex Validation Layer never silently swallows a violation. Every
block writes a `.draft.md` under `docs/codex/_drafts/` describing the
proposed action, the rule it tripped, and the choices the operator has
to resolve it. Draft filenames are suffixed `.draft.md` so they can't be
confused with real ADRs and are gitignored (see `.gitignore`).
"""

from __future__ import annotations

import json
import os
import re
from datetime import datetime, timezone
from pathlib import Path

from .models import ProposedAction
from .registry import CodexRegistry


_DRAFTS_SUBDIR = "_drafts"
_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _default_drafts_dir() -> Path:
    """Resolve drafts dir, preferring the writable state root in containers.

    In production containers the image is read-only and the codex tree at
    /opt/samus/docs/codex/ is immutable. Drafts must land in the writable
    state root (/opt/samus/data, mirrored to host) via SAMUS_STATE_ROOT.
    SAMUS_CODEX_DRAFTS_DIR explicitly overrides both for tests.
    """
    explicit = os.environ.get("SAMUS_CODEX_DRAFTS_DIR", "").strip()
    if explicit:
        return Path(explicit)
    state_root = os.environ.get("SAMUS_STATE_ROOT", "").strip()
    if state_root:
        return Path(state_root) / "codex_drafts"
    return Path(__file__).resolve().parents[3] / "docs" / "codex" / _DRAFTS_SUBDIR


def _slugify(value: str) -> str:
    return _SLUG_RE.sub("-", value.lower()).strip("-") or "action"


def _next_adr_number(registry: CodexRegistry) -> int:
    highest = 0
    for adr in registry.adrs():
        match = re.match(r"ADR-(\d{3,})", adr.id)
        if match:
            highest = max(highest, int(match.group(1)))
    return highest + 1


def draft_adr_for_violation(
    action: ProposedAction,
    violated_rule_id: str,
    reason: str,
    registry: CodexRegistry,
    drafts_dir: Path | None = None,
) -> Path:
    target_dir = drafts_dir or _default_drafts_dir()
    target_dir.mkdir(parents=True, exist_ok=True)

    next_n = _next_adr_number(registry)
    adr_id = f"ADR-{next_n:03d}"
    slug = _slugify(action.action_kind)
    path = target_dir / f"{adr_id}_{slug}.draft.md"

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    payload_json = json.dumps(action.payload, indent=2, sort_keys=True, default=str)
    correlation = action.correlation_id or "(none)"

    body = (
        f"# {adr_id} (DRAFT) — {action.action_kind} blocked by {violated_rule_id}\n"
        "\n"
        "> **Status: DRAFT — requires operator decision before this ADR can be\n"
        "> moved to `08_decisions_log.md`. Action remains blocked until then.**\n"
        "\n"
        f"**Date:** {now_utc} (auto, UTC)\n"
        f"**Triggered by:** `{action.service}.{action.capability}` proposing "
        f"`{action.action_kind}`\n"
        f"**Correlation ID:** `{correlation}`\n"
        f"**Violated rule:** `{violated_rule_id}`\n"
        f"**Reason:** {reason}\n"
        "\n"
        "## Proposed action (raw)\n"
        "\n"
        "```json\n"
        f"{payload_json}\n"
        "```\n"
        "\n"
        "## Decision required\n"
        "\n"
        "Choose ONE:\n"
        "\n"
        "- **A — ALLOW (with constraints):** Author a real ADR in\n"
        "  `docs/codex/08_decisions_log.md` explaining why this action is\n"
        "  permitted, what new gates accompany it, and what failure modes it\n"
        "  introduces. Reference any prior ADRs it supersedes. Then move this\n"
        "  draft to `_resolved/` and commit.\n"
        "- **B — REJECT:** Modify the code so this action no longer triggers the\n"
        "  violation. Delete this draft file.\n"
        "\n"
        "## Why this draft exists\n"
        "\n"
        "The Codex Validation Layer (chapter 12 / ADR-011) caught this proposed\n"
        f"action under rule `{violated_rule_id}` and refuses to let it run until a\n"
        "real decision is recorded. This is the discipline that keeps the system\n"
        "honest when nobody is watching.\n"
        "\n"
        "— autogenerated by `backend/common/codex/adr_drafter.py`\n"
    )

    # write_bytes, not write_text: force LF on Windows too. write_text uses
    # text mode and would translate \n -> \r\n, churning the LF-normalized
    # tracked drafts under docs/codex/_drafts/ into whole-file EOL diffs.
    path.write_bytes(body.encode("utf-8"))
    return path.resolve()


__all__ = [
    "draft_adr_for_violation",
]
