<#
.SYNOPSIS
  Run the morning Vapi autodialer against today's prospect call list.

.DESCRIPTION
  Wraps ``python -m backend.voice.dialer`` with the secret-handling +
  approval-gate pattern other Samus operator scripts use:

    1. Pull VAPI_API_KEY, VAPI_ASSISTANT_ID, VAPI_PHONE_NUMBER_ID from DPAPI
       (Scope=Samus). Set them only on this process's env, scrub in finally.
    2. Default to DRY-RUN so the operator approves before any real call
       is placed. Pass ``-Live`` to actually dial.
    3. Forward CSV path / max-calls / TCPA-gate / priority filters to the
       Python CLI.

  Per-prospect calls are placed via Vapi's REST API. Each attempt is
  appended to ``<artifact_root>/voice/voice_audit.jsonl`` and the run
  aggregate is written to ``<artifact_root>/voice/dial_runs/<run_id>.json``.

  Prereqs (one-time):

    Set-HfSecret -Scope Samus -Name VapiApiKey
    Set-HfSecret -Scope Samus -Name VapiAssistantId
    Set-HfSecret -Scope Samus -Name VapiPhoneNumberId

  Today's CSV is generated by the prospecting workcell's daily run; if it
  doesn't exist the script aborts (state-mismatch is a STOP).

.PARAMETER Live
  Actually place calls. Default = dry-run, no calls placed.

.PARAMETER MaxCalls
  Hard cap on calls per run. Default 5; max 50.

.PARAMETER Csv
  Override the CSV path. Default is today's call_list_YYYY-MM-DD.csv
  under <artifact_root>/daily_calls/.

.PARAMETER DelaySeconds
  Wall-clock seconds between successive dial attempts. Default 30.

.PARAMETER Priorities
  Comma-separated priority buckets to include (hot, warm, low).
  Default 'hot,warm'.

.PARAMETER DisableTcpa
  Skip the per-prospect TCPA hours gate (8am-9pm prospect-local).
  Operator owns TCPA risk in that mode.

.EXAMPLE
  .\Start-MorningDial.ps1                            # dry-run, 5 prospects
  .\Start-MorningDial.ps1 -Live -MaxCalls 3          # live, 3 prospects
  .\Start-MorningDial.ps1 -Live -Priorities hot      # live, hot-only
#>

[CmdletBinding()]
param(
    [Parameter()][switch]$Live,
    [Parameter()][int]$MaxCalls = 5,
    [Parameter()][string]$Csv,
    [Parameter()][double]$DelaySeconds = 30.0,
    [Parameter()][string]$Priorities = "hot,warm",
    [Parameter()][switch]$DisableTcpa
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$samusRoot = Resolve-Path (Join-Path $here '..')
$venvPython = Join-Path $samusRoot '.venv\Scripts\python.exe'
if (-not (Test-Path $venvPython)) {
    # Worktrees share the main checkout's venv (D:\Hustleforge\Samus\.venv).
    $mainVenvPython = 'D:\Hustleforge\Samus\.venv\Scripts\python.exe'
    if (Test-Path $mainVenvPython) {
        $venvPython = $mainVenvPython
    } else {
        throw "venv python not found at $venvPython or $mainVenvPython. Run scripts\Bootstrap-Samus.ps1 first."
    }
}

# DPAPI secret pull.
$sharedModule = 'D:\Hustleforge\_shared\scripts\Hustleforge.Secrets.psm1'
if (-not (Test-Path $sharedModule)) {
    throw "Shared secrets module not found at $sharedModule"
}
Import-Module $sharedModule -Force

$required = @(
    @{ DpapiName='VapiApiKey';        EnvVar='VAPI_API_KEY' },
    @{ DpapiName='VapiAssistantId';   EnvVar='VAPI_ASSISTANT_ID' },
    @{ DpapiName='VapiPhoneNumberId'; EnvVar='VAPI_PHONE_NUMBER_ID' },
    @{ DpapiName='AwsAccessKeyId';     EnvVar='AWS_ACCESS_KEY_ID' },
    @{ DpapiName='AwsSecretAccessKey'; EnvVar='AWS_SECRET_ACCESS_KEY' },
    @{ DpapiName='WordPressUsername';    EnvVar='WORDPRESS_USERNAME' },
    @{ DpapiName='WordPressAppPassword'; EnvVar='WORDPRESS_APP_PASSWORD' }
)
$missing = @()
foreach ($s in $required) {
    if (-not (Test-HfSecret -Scope Samus -Name $s.DpapiName)) {
        $missing += $s.DpapiName
    }
}
if ($missing.Count -gt 0) {
    Write-Warning "Missing required DPAPI secrets: $($missing -join ', ')"
    Write-Warning "Populate with: Set-HfSecret -Scope Samus -Name <Name>"
    throw "Aborting -- required Vapi secrets are not in the DPAPI store."
}

# Build the python CLI args.
# LIVE Vapi numbers only — the call list is divided into equal chunks, one per
# number, so any dead id silently fails its whole chunk. Verified against
# `GET https://api.vapi.ai/phone-number` on 2026-06-30: only these two are
# `active`. The four previously-listed ids (a0d742b4, b93fbb87, 8554830e,
# 4e944525, 33842c67) no longer exist in Vapi — keeping them routed 4/6 of every
# batch to numbers that reject the call. Routine pool = the two TWILIO-OWNED
# numbers (operator decision 2026-07-02): f775b297 = (530) 418-5105 (primary,
# Morgan's number); 24b2b17a = (530) 792-9146 (imported 2026-07-02,
# Morgan-bound). 21f79fb4 = (530) 220-1858 (marketing 2) is VAPI-NATIVE and
# limited-use — kept OUT of the daily rotation; add it back explicitly via
# a manual run only when extra capacity is needed. Re-verify with the
# phone-number API before adding more.
$allPhoneNumberIds = 'f775b297-b268-4763-bc8d-59fc0ae75cdc,' +
                     '24b2b17a-5caa-4320-81fe-855403c5f6af'

# Resolve CSV path early so we can validate it before decrypting secrets.
$resolvedCsv = if ($Csv) { $Csv } else {
    $today = (Get-Date).ToString('yyyy-MM-dd')
    $artifactRoot = if ($env:SAMUS_ARTIFACT_ROOT) { $env:SAMUS_ARTIFACT_ROOT } else { 'D:\Hustleforge\Samus\.data\host_artifacts' }
    Join-Path $artifactRoot "daily_calls\call_list_$today.csv"
}
if (-not (Test-Path $resolvedCsv)) {
    throw "Call list CSV not found: $resolvedCsv -- prospecting workcell must run first."
}
$lineCount = (Get-Content $resolvedCsv | Measure-Object -Line).Lines
if ($lineCount -le 1) {
    throw "Call list CSV is empty (only a header row or blank): $resolvedCsv -- aborting to avoid a zero-call run."
}
Write-Host "==> CSV: $resolvedCsv ($($lineCount - 1) data rows)"

$pyArgs = @('-m', 'backend.voice.dialer', '--max', $MaxCalls,
            '--delay', $DelaySeconds.ToString([System.Globalization.CultureInfo]::InvariantCulture),
            '--phone-number-ids', $allPhoneNumberIds)
$pyArgs += @('--csv', $resolvedCsv)
if ($Live) { $pyArgs += '--live' }
if ($DisableTcpa) { $pyArgs += '--disable-tcpa' }
foreach ($p in ($Priorities -split ',' | ForEach-Object { $_.Trim().ToLower() })) {
    if ($p -in @('hot','warm','low')) {
        $pyArgs += @('--priority', $p)
    }
}

Write-Host ""
if ($Live) {
    Write-Host "==> Running LIVE dialer (calls WILL be placed)" -ForegroundColor Red
} else {
    Write-Host "==> Running DRY-RUN dialer (no calls placed; pass -Live to dial)" -ForegroundColor Cyan
}

$exported = @()
try {
    foreach ($s in $required) {
        Set-Item -Path "Env:$($s.EnvVar)" -Value (Get-HfSecret -Scope Samus -Name $s.DpapiName)
        $exported += $s.EnvVar
    }
    $env:AWS_REGION = 'us-west-1'
    $exported += 'AWS_REGION'
    $env:SAMUS_ENV = 'production'
    $exported += 'SAMUS_ENV'
    # Pin artifact root so storage.root() writes dial_run files to the same
    # host_artifacts tree that prospecting writes the call list from — required
    # for _already_called_today to find today's run files and prevent re-dials.
    $env:SAMUS_ARTIFACT_ROOT = 'D:\Hustleforge\Samus\.data\host_artifacts'
    $exported += 'SAMUS_ARTIFACT_ROOT'
    # Ledger integrity: seed the hash-chained audit ledger key (optional; the
    # ledger fails soft without it, recording only to the local JSONL). Same
    # DPAPI->env mapping Start-SamusStack uses.
    if (Test-HfSecret -Scope Samus -Name SharedHmacKey) {
        $env:SAMUS_SHARED_HMAC_KEY = Get-HfSecret -Scope Samus -Name SharedHmacKey
        $exported += 'SAMUS_SHARED_HMAC_KEY'
    } elseif ($Live) {
        Write-Warning "SharedHmacKey missing -- voice audit ledger will stay unavailable on this live run."
    }
    Push-Location $samusRoot
    try {
        & $venvPython @pyArgs
        $exitCode = $LASTEXITCODE
    } finally {
        Pop-Location
    }
} finally {
    foreach ($var in $exported) {
        Remove-Item -Path "Env:$var" -ErrorAction SilentlyContinue
    }
}

if ($exitCode -ne 0) {
    Write-Warning "Dialer exited with code $exitCode"
    exit $exitCode
}
